package com.brainboost.brainboost.auth.dto.enums;

public enum PermissionEnum {
    ADD_USER_PERMISSION,
    EDIT_USER_PERMISSION,
    VIEW_USER_PERMISSION,
    DELETE_USER_PERMISSION,
    VIEW_COURSE_PERMISSION,
    EDIT_COURSE_PERMISSION,
    DELETE_COURSE_PERMISSION,
    ADD_COURSE_PERMISSION,
    VIEW_TEACHER_PERMISSION,
    DELETE_TEACHER_PERMISSION,
    VIEW_STUDENT_PERMISSION,
    EDIT_STUDENT_PERMISSION,
}
